import Head from 'next/head'
import {motion} from "framer-motion"
import Navbar from '@/components/navbar/Navbar'

export default function Home() {
  return (
    <motion.div
    initial={{ opacity: 0 }}
    whileInView={{ opacity: 1 }}
    viewport={{ once: true }}
    className="  dark:text-gray-400 scrollbar-hide max-h-screen overflow-auto"
  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
    </motion.div>
  )
}
