import Head from 'next/head'
import {motion} from "framer-motion"
import Navbar from '@/components/navbar/Navbar'
import HeroSection from '@/components/content/HeroSection' 
import HeadlineCards from '@/components/content/HeadlineCards'
import FoodSection from '@/components/content/FoodSection'
import CategorySection from '@/components/content/CategorySection'
import CartSidebar from '@/components/sidebar/CartSidebar'
import CartToggle from '@/components/sidebar/CartToggle'
import Footer from '@/components/footer/Footer'

export default function Home() {
  return (
    <motion.div
    initial={{ opacity: 0 }}
    whileInView={{ opacity: 1 }}
    viewport={{ once: true }}
    className="  dark:text-gray-400 scrollbar-hide max-h-screen overflow-auto"
  >
      <Head>
        <title>Daves Eatery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://duyt4h9nfnj50.cloudfront.net/new_search_home_eats_icon/Pizza_BrowseHome@3x.png" />
      </Head>
      <Navbar/>
      <main className='mt-20'>
        <HeroSection/>
        <HeadlineCards/>
        <FoodSection/>
        <CategorySection/>
        <CartSidebar/>
        <CartToggle/>
        <Footer/>
      </main>
    </motion.div>
  )
}
